global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nifi'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'airflow'
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'spark'
    static_configs:
      - targets: ['localhost:8082']

  - job_name: 'minio'
    static_configs:
      - targets: ['localhost:9000']
